Add a switch theme option on the dashboard
eric-taix/volley34-mobile pull request #58
Opened 2020-07-04 11:18 UTC by thomasFoulon

Close #47 
I added a switch button to permit the user to switch between a light and a dark theme on the dashboard. There is also a "circle clipper" animation (thanks to a package I found) to have a smooth switching.

<img src="https://user-images.githubusercontent.com/67117547/86511322-4aa3a880-bdf8-11ea-97fb-6e125b1ff000.jpg" height=400>
<img src="https://user-images.githubusercontent.com/67117547/86511321-48d9e500-bdf8-11ea-8178-ce1c1e1adc31.jpg" height=400>

2020-07-04 11:20 UTC, thomasFoulon commented on lib/main.dart
> +  void initState() {
To delete, because useless.

2020-07-04 11:21 UTC, thomasFoulon commented on lib/pages/dashboard/dashoard_page.dart
> +import 'package:v34/main.dart';
To remove

2020-07-06 11:19 UTC, eric-taix-teads commented
I've played a bit with your branch yesterday, and even if it's a first step we'll have to add a menu somewhere because:
  - switching the theme is not a main action and adding this switch on the main screen adds some noise into the UX. 
  - a second switch must be added to use the auto dark theme feature, if enabled
  - I'd like to display somewhere the contributors of the project (dev + testers)

But this is not required right now: let's merge this one first.

2020-07-06 11:55 UTC, thomasFoulon commented
Ok, I can change it now, I'll add a menu !
Do I add a gearwheel icon at the same place as the switch button ?
And what do you think about my light theme ?

2020-07-06 12:26 UTC, eric-taix commented
I think that a gearwheel will be fine, but you should also add an app bar
as floating buttons are "reserved" for actions in the current page.
This app bar can be dismissed when the user scrolls down and can be
displayed again when the user scrolls up (no matter the scroll position)

Le lun. 6 juil. 2020 à 13:56, thomasFoulon <notifications@github.com> a
écrit :

> Ok, I can change it now, I'll add a menu !
> Do I add a gearwheel icon at the same place as the switch button ?
> And what do you think about my light theme ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eric-taix/volley34-mobile/pull/58#issuecomment-654188683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFN6RLABBWCCYFSX3FILY3R2G3VTANCNFSM4OQLMGRQ>
> .
>

2020-07-06 12:27 UTC, eric-taix commented
The light theme is a good starting point even if I think it could be more
bright (white)

Le lun. 6 juil. 2020 à 14:25, Eric Taix <eric.taix@gmail.com> a écrit :

> I think that a gearwheel will be fine, but you should also add an app bar
> as floating buttons are "reserved" for actions in the current page.
> This app bar can be dismissed when the user scrolls down and can be
> displayed again when the user scrolls up (no matter the scroll position)
>
> Le lun. 6 juil. 2020 à 13:56, thomasFoulon <notifications@github.com> a
> écrit :
>
>> Ok, I can change it now, I'll add a menu !
>> Do I add a gearwheel icon at the same place as the switch button ?
>> And what do you think about my light theme ?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/eric-taix/volley34-mobile/pull/58#issuecomment-654188683>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAFN6RLABBWCCYFSX3FILY3R2G3VTANCNFSM4OQLMGRQ>
>> .
>>
>

2020-07-07 13:58 UTC, thomasFoulon commented
Here is the new way to switch theme with a menu. Also note that the app bar is dismissed when the user scrolls down and is displayed again when the user scrolls up.
<img src="https://user-images.githubusercontent.com/67117547/86792176-8645a900-c06a-11ea-945d-3cf60af81052.jpg" height=400>
<img src="https://user-images.githubusercontent.com/67117547/86792192-880f6c80-c06a-11ea-8585-9005f9971ceb.jpg" height=400>
<img src="https://user-images.githubusercontent.com/67117547/86792201-89409980-c06a-11ea-9ede-5cd74f0da905.jpg" height=400>

2020-07-07 14:05 UTC, eric-taix-teads commented
👏 👏 👏

2020-07-07 14:08 UTC, eric-taix-teads commented
When this PR will be merged into master and deployed to the store, can you write a message to beta user group in whatapps with some screenshots to inform them that a new version is available and to get their opinions?

2020-07-07 14:10 UTC, eric-taix-teads commented on lib/pages/dashboard/dashoard_page.dart
> +  void _pushPreferences() {
`_gotoPreferencesPage()`? `_push` is really technical

2020-07-07 14:11 UTC, eric-taix-teads commented on lib/pages/dashboard/fav_club_card.dart
> +                          style: TextStyle(fontSize: 24.0, fontWeight: FontWeight.bold, color: Theme.of(context).textTheme.bodyText2.color),
👍

2020-07-07 14:12 UTC, eric-taix-teads commented on lib/pages/preferences_page.dart
> +                  "Cette option activera le mode sombre le soir et le désactivera le matin.",
```suggestion
                  "Cette option active automatiquement le mode sombre le soir et le désactive le matin.",
```

2020-07-07 14:15 UTC, eric-taix-teads commented on lib/theme.dart
> +  static ThemeData orangeTheme() {
What is this theme for?

2020-07-07 14:17 UTC, eric-taix-teads commented on lib/main.dart
> +  void initState() {
Not more useless

2020-07-07 14:19 UTC, eric-taix-teads commented on lib/main.dart
> +      if (now.hour >= 20 || now.hour < 8) return AppTheme.darkTheme();
I have seen this test twice in this PR. You can probably factorize them in a function / method, to be sure that any change will be applied everywhere

2020-07-07 14:19 UTC, thomasFoulon commented
Thanks ! :smile: 

I tested the automatic dark theme by changing the time on my phone and it works but only when the application is closed (not in  the cache anymore). Do you know a way to pass in dark theme at 20 o'clock (the hour I chose) even if the application still in the cache ?

And what do you think about 8 o'clock AM and 8 o'clock PM for automatic theme switching ?

2020-07-07 14:21 UTC, eric-taix-teads commented on lib/pages/dashboard/dashoard_page.dart
> +                title: Text('Tableau de bord'),
As the dashboard is the main page, I think that reusing the application's name is a good pattern. In other pages we will use the a real title

2020-07-07 14:23 UTC, eric-taix commented
I think the hours depend on the sun: black theme for the night and light
theme for the day (so it also depends on the month and where you're
leaving, even if it does not really matter for this application)

Le mar. 7 juil. 2020 à 16:19, thomasFoulon <notifications@github.com> a
écrit :

> Thanks ! 😄
>
> I tested the automatic dark theme by changing the time on my phone and it
> works but only when the application is closed (not in the cache anymore).
> Do you know a way to pass in dark theme at 20 o'clock (the hour I chose)
> even if the application still in the cache ?
>
> And what do you think about 8 o'clock AM and 8 o'clock PM for automatic
> theme switching ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/eric-taix/volley34-mobile/pull/58#issuecomment-654896447>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFN6RORTQ57XLCTBT3V4DDR2MVIJANCNFSM4OQLMGRQ>
> .
>

2020-07-07 15:06 UTC, thomasFoulon commented
I have taken into consideration all you comments !

2020-07-07 15:07 UTC, thomasFoulon commented
Do we implement the sun relative theme switching ?

2020-07-08 08:33 UTC, merged

2024-12-05 15:33 UTC, Zulu-1540 requested changes
Spam my WhatsApp

2024-12-05 15:54 UTC, Zulu-1540 requested changes
Spam and hacker
Please take it seriously